# Generated by Django 2.2.5 on 2019-11-20 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('profile_info', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_pic', models.CharField(max_length=300)),
                ('MyUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_pic', models.CharField(max_length=300)),
                ('MyUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.MyUser')),
            ],
        ),
    ]
