# Generated by Django 2.2.5 on 2020-01-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_info',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
